### ISSUE TITLE
Matplotlib-related crash

### ISSUE THREAD

**Issue by Anthchirp** [xia2/screen19#11]
see 0d9f853c6565e704691824fc6f429d5442f1a3bd

If `semilogy` is to blame then this instance may also crash conditionally on overloads being present:
https://github.com/xia2/screen19/blob/0d9f853c6565e704691824fc6f429d5442f1a3bd/screen19/screen.py#L212

**Comment by ndevenish** [comment]
Just spoke to Ben about this - yes, a while ago matplotlib changed the logscale-drawing-functions to not avoid dividing by zero.

This then runs into the default `boost_adaptbx` FPE-crashing functions. I found the commit a while ago that changed this in matplotlib but didn't think it was completely reasonable to ask to change, as handling FPE's is normally part of a working programs job, and dividing by zero just gives a NaN, which is then handled.

Setting the BOOST_ADAPTBX_FPE_WHATEVER flag seems to work, but IIRC there is a canonical way to temporarily pause the capturing?

(Also pointed out: `.semilogy` is the *plotting* function for plots log in y. Probably meant to do `plt.yscale("log")` instead)

**Comment by ndevenish** [comment]
Apparently 
```python
boost.python.floating_point_exceptions.division_by_zero_trapped = False
```
is the way to turn it off. If we wanted to keep the behaviour, we should probably wrap this in a context handler.
