### ISSUE TITLE
Remove support for dials 1.x series

### ISSUE THREAD

**Issue by graeme-winter** [xia2/screen19#23]
Will help the code to be more easily interpreted 🙂

Stumbled across this, thought should record $somewhere

**Comment by benjaminhwilliams** [comment]
On it.

**Comment by Anthchirp** [comment]
Bear in mind that the current stable release version of DIALS in CCP4 is still 1.14.

I would keep this around until CCP4 have moved on

**Comment by benjaminhwilliams** [comment]
I mentioned that to @graeme-winter but he said they were on 2.x.  But I'm working on a branch anyway, so there's no danger, except for merge conflicts as this branch and master diverge.

**Comment by Anthchirp** [comment]
7.1 is on 2.1.0, but that's not released yet.

**Comment by benjaminhwilliams** [comment]
OK, good, I'll tread carefully.
