### ISSUE TITLE
Automate pre-commit hook updates

### ISSUE THREAD

**Issue by benjaminhwilliams** [xia2/screen19#34]
Write a GitHub action to periodically do the following:
 1. Check out the module.
 1. Set up Python.
 1. Run `pip install pre-commit`.
 1. Run `pre-commit autoupdate`.
 1. Run `pre-commit run --all-files`.
 1. If the branch `pre-commit-autoupdate` exists, merge `master` into this branch (or should we delete it, along with any associated open PR, and branch again from the current state of `master`?).  Otherwise, make that branch and check it out.
 1. Commit the changes.
 1. If there isn't already one, open a pull request and commit a corresponding pro forma Towncrier `.misc` news fragment.
 1. If the only changes are contained in `.pre-commit-config.yaml` (i.e. version number changes) and the news fragment, then merge?

Some further refinements to that workflow are probably necessary.

**Comment by Anthchirp** [comment]
>6. If the branch `pre-commit-autoupdate` exists, merge `master` into this branch (or should we delete it, along with any associated open PR, and branch again from the current state of `master`?).  Otherwise, make that branch and check it out.

Suggest delete, ie. just create a new one off HEAD and force-push.

> 9. If the only changes are contained in `.pre-commit-config.yaml` (i.e. version number changes) and the news fragment, then merge?

I would leave auto-merging as out of scope. You want to merge only when tests pass anyway, but you don't want to monitor this from the PR-creating action.

**Comment by benjaminhwilliams** [comment]
Good points, thanks.

**Comment by benjaminhwilliams** [comment]
Workflow now more like:
 1. Check out the module.
 1. Set up Python.
 1. Run `pip install pre-commit`.
 1. Run `pre-commit autoupdate`.
 1. Run `pre-commit run --all-files`.
 1. Run `git checkout -B pre-commit-autoupdate`.
 1. Commit the changes.
 1. Force-push the commit.
 1. If there isn't already one, open a pull request and commit & push a corresponding pro forma Towncrier `.misc` news fragment.

**Comment by benjaminhwilliams** [comment]
Useful inspiration here:
https://dev.to/browniebroke/auto-update-pre-commit-hooks-with-github-actions-3f84
