### ISSUE TITLE
Add feature to I19.screen to estimate the Wilson B factor...

### ISSUE THREAD

**Issue by graeme-winter** [xia2/screen19#4]
so we can estimate the increase in transmission needed to e.g. go from 2theta = 0 to 30 or 30 to 55 (say)

DA has student (Daniel Tchon) for couple months, will look into this...

**Comment by graeme-winter** [comment]
Thoughts: start with an isotropic model then look at anisotropic. Constraining parameters by crystal symmetry axes would also be nice: see dials refinement crystal parameterisation for inspiration

**Comment by Anthchirp** [comment]
https://jira.diamond.ac.uk/browse/SCI-7610

**Comment by benjaminhwilliams** [comment]
Long-since done.
